let movies = [
  {
    id: "1",
    title: "Inception",
    director_id: "1",
    genre: "Science Fiction",
    year: 2010,
    duration: "2h 28min",
    budget: "$160 million",
  },
  {
    id: "2",
    title: "The Shawshank Redemption",
    director_id: "2",
    genre: "Drama",
    year: 1994,
    duration: "2h 22min",
    budget: "$25 million",
  },
  {
    id: "3",
    title: "The Godfather",
    director_id: "3",
    genre: "Crime",
    year: 1972,
    duration: "2h 55min",
    budget: "$6-7 million",
  },
  {
    id: "4",
    title: "The Dark Knight",
    director_id: "1",
    genre: "Action",
    year: 2008,
    duration: "2h 32min",
    budget: "$185 million",
  },
  {
    id: "5",
    title: "Schindler's List",
    director_id: "4",
    genre: "Biography",
    year: 1993,
    duration: "3h 15min",
    budget: "$22 million",
  },
  {
    id: "6",
    title: "Avatar",
    director_id: "6",
    genre: "Action",
    year: 2009,
    duration: "2h 42min",
    budget: "$237 million",
  },
  {
    id: "7",
    title: "Goodfellas",
    director_id: "7",
    genre: "Biography",
    year: 1990,
    duration: "2h 26min",
    budget: "$25 million",
  },
  {
    id: "8",
    title: "Psycho",
    director_id: "8",
    genre: "Horror",
    year: 1960,
    duration: "1h 49min",
    budget: "$806,947",
  },
  {
    id: "9",
    title: "The Shining",
    director_id: "9",
    genre: "Horror",
    year: 1980,
    duration: "2h 26min",
    budget: "$19 million",
  },
  {
    id: "10",
    title: "Terminator 2: Judgment Day",
    director_id: "6",
    genre: "Action",
    year: 1991,
    duration: "2h 17min",
    budget: "$102 million",
  },
  {
    id: "11",
    title: "Raging Bull",
    director_id: "7",
    genre: "Biography",
    year: 1980,
    duration: "2h 9min",
    budget: "$18 million",
  },
  {
    id: "12",
    title: "Vertigo",
    director_id: "8",
    genre: "Mystery",
    year: 1958,
    duration: "2h 8min",
    budget: "$2.5 million",
  },
  {
    id: "13",
    title: "2001: A Space Odyssey",
    director_id: "9",
    genre: "Sci-Fi",
    year: 1968,
    duration: "2h 29min",
    budget: "$10.5 million",
  },
  {
    id: "14",
    title: "Aliens",
    director_id: "6",
    genre: "Action",
    year: 1986,
    duration: "2h 17min",
    budget: "$18.5 million",
  },
  {
    id: "15",
    title: "Taxi Driver",
    director_id: "7",
    genre: "Drama",
    year: 1976,
    duration: "1h 54min",
    budget: "$1.3 million",
  },
  {
    id: "16",
    title: "Interstellar",
    director_id: "1",
    genre: "Sci-Fi",
    year: 2014,
    duration: "2h 49min",
    budget: "$165 million",
  },
  {
    id: "17",
    title: "Dunkirk",
    director_id: "1",
    genre: "Action",
    year: 2017,
    duration: "1h 46min",
    budget: "$100-150 million",
  },
  {
    id: "18",
    title: "The Green Mile",
    director_id: "2",
    genre: "Drama",
    year: 1999,
    duration: "3h 9min",
    budget: "$60 million",
  },
  {
    id: "19",
    title: "The Mist",
    director_id: "2",
    genre: "Horror",
    year: 2007,
    duration: "2h 6min",
    budget: "$18 million",
  },
  {
    id: "20",
    title: "Apocalypse Now",
    director_id: "3",
    genre: "War",
    year: 1979,
    duration: "2h 27min",
    budget: "$31.5 million",
  },
  {
    id: "21",
    title: "The Outsiders",
    director_id: "3",
    genre: "Drama",
    year: 1983,
    duration: "1h 31min",
    budget: "$10 million",
  },
  {
    id: "22",
    title: "Jurassic Park",
    director_id: "4",
    genre: "Sci-Fi",
    year: 1993,
    duration: "2h 7min",
    budget: "$63 million",
  },
  {
    id: "23",
    title: "Saving Private Ryan",
    director_id: "4",
    genre: "Drama",
    year: 1998,
    duration: "2h 49min",
    budget: "$70 million",
  },
];

let directors = [
  {
    id: "1",
    name: "Christopher Nolan",
    nationality: "British",
    birth_year: 1970,
  },
  {
    id: "2",
    name: "Frank Darabont",
    nationality: "American",
    birth_year: 1959,
  },
  {
    id: "3",
    name: "Francis Ford Coppola",
    nationality: "American",
    birth_year: 1939,
  },
  {
    id: "4",
    name: "Steven Spielberg",
    nationality: "American",
    birth_year: 1946,
  },
  {
    id: "5",
    name: "Quentin Tarantino",
    nationality: "American",
    birth_year: 1963,
  },
  { id: "6", name: "James Cameron", nationality: "Canadian", birth_year: 1954 },
  {
    id: "7",
    name: "Martin Scorsese",
    nationality: "American",
    birth_year: 1942,
  },
  {
    id: "8",
    name: "Alfred Hitchcock",
    nationality: "British",
    birth_year: 1899,
  },
  {
    id: "9",
    name: "Stanley Kubrick",
    nationality: "American",
    birth_year: 1928,
  },
];

let reviews = [
  {
    id: "1",
    rating: 9,
    content: "A mind-bending masterpiece",
    reviewer_name: "John Doe",
    movie_id: "1",
  },
  {
    id: "2",
    rating: 10,
    content: "One of the greatest movies ever made",
    reviewer_name: "Jane Smith",
    movie_id: "2",
  },
  {
    id: "3",
    rating: 7,
    content: "A classic crime drama",
    reviewer_name: "Alice Johnson",
    movie_id: "3",
  },
  {
    id: "4",
    rating: 5,
    content: "Not as good as expected",
    reviewer_name: "Bob Williams",
    movie_id: "4",
  },
  {
    id: "5",
    rating: 8,
    content: "An excellent movie with great performances",
    reviewer_name: "Emma Thompson",
    movie_id: "5",
  },
  {
    id: "6",
    rating: 9,
    content: "A must-watch movie with a touching story",
    reviewer_name: "Michael Scott",
    movie_id: "1",
  },
  {
    id: "7",
    rating: 10,
    content: "Mind-blowing action and stunning visuals",
    reviewer_name: "Sarah Johnson",
    movie_id: "2",
  },
  {
    id: "8",
    rating: 7,
    content: "Emotionally intense and superbly acted",
    reviewer_name: "David Johnson",
    movie_id: "3",
  },
  {
    id: "9",
    rating: 8,
    content: "Riveting performances and captivating storyline",
    reviewer_name: "John Smith",
    movie_id: "4",
  },
  {
    id: "10",
    rating: 9,
    content: "Brilliantly directed and acted",
    reviewer_name: "Emily Davis",
    movie_id: "5",
  },
  {
    id: "11",
    rating: 7,
    content: "A bit slow-paced but emotionally powerful",
    reviewer_name: "Michael Brown",
    movie_id: "1",
  },
  {
    id: "12",
    rating: 8,
    content: "Compelling story and strong performances",
    reviewer_name: "Sophia Martinez",
    movie_id: "2",
  },
  {
    id: "13",
    rating: 9,
    content: "Visually stunning and emotionally resonant",
    reviewer_name: "Daniel Johnson",
    movie_id: "3",
  },
  {
    id: "14",
    rating: 10,
    content: "An absolute masterpiece of cinema",
    reviewer_name: "Olivia Wilson",
    movie_id: "4",
  },
  {
    id: "15",
    rating: 8,
    content: "Great cinematography and gripping narrative",
    reviewer_name: "Noah Taylor",
    movie_id: "5",
  },
  {
    id: "16",
    rating: 8,
    content: "Captivating storyline and impressive visuals",
    reviewer_name: "John Doe",
    movie_id: "6",
  },
  {
    id: "17",
    rating: 9,
    content: "A groundbreaking film with stunning special effects",
    reviewer_name: "Jane Smith",
    movie_id: "7",
  },
  {
    id: "18",
    rating: 7,
    content: "Engaging performances but pacing issues",
    reviewer_name: "Alice Johnson",
    movie_id: "8",
  },
  {
    id: "19",
    rating: 6,
    content: "Disappointing adaptation of the novel",
    reviewer_name: "Bob Williams",
    movie_id: "9",
  },
  {
    id: "20",
    rating: 8,
    content: "Gripping action and emotional depth",
    reviewer_name: "Emma Thompson",
    movie_id: "10",
  },
  {
    id: "21",
    rating: 7,
    content: "Solid entertainment with memorable characters",
    reviewer_name: "John Doe",
    movie_id: "11",
  },
  {
    id: "22",
    rating: 9,
    content: "Compelling portrayal of organized crime",
    reviewer_name: "Jane Smith",
    movie_id: "12",
  },
  {
    id: "23",
    rating: 8,
    content: "Masterful suspense and psychological depth",
    reviewer_name: "Alice Johnson",
    movie_id: "13",
  },
  {
    id: "24",
    rating: 10,
    content: "An iconic horror film that stands the test of time",
    reviewer_name: "Bob Williams",
    movie_id: "14",
  },
  {
    id: "25",
    rating: 7,
    content: "A thrilling sci-fi adventure with groundbreaking effects",
    reviewer_name: "Emma Thompson",
    movie_id: "15",
  },
  {
    id: "26",
    rating: 9,
    content: "Epic storytelling and breathtaking visuals",
    reviewer_name: "John Doe",
    movie_id: "16",
  },
  {
    id: "27",
    rating: 8,
    content: "Intense and gripping from start to finish",
    reviewer_name: "Jane Smith",
    movie_id: "17",
  },
  {
    id: "28",
    rating: 9,
    content: "Riveting performances and compelling narrative",
    reviewer_name: "Alice Johnson",
    movie_id: "18",
  },
  {
    id: "29",
    rating: 7,
    content: "Solid direction but lacks originality",
    reviewer_name: "Bob Williams",
    movie_id: "19",
  },
  {
    id: "30",
    rating: 8,
    content: "Engaging storyline and strong character development",
    reviewer_name: "Emma Thompson",
    movie_id: "20",
  },
  {
    id: "31",
    rating: 9,
    content: "Intriguing plot twists and memorable moments",
    reviewer_name: "John Doe",
    movie_id: "21",
  },
  {
    id: "32",
    rating: 7,
    content: "Impressive cinematography but uneven pacing",
    reviewer_name: "Jane Smith",
    movie_id: "22",
  },
  {
    id: "33",
    rating: 8,
    content: "Authentic portrayal of historical events",
    reviewer_name: "Alice Johnson",
    movie_id: "23",
  },
  {
    id: "34",
    rating: 9,
    content: "Visually stunning and emotionally resonant",
    reviewer_name: "Bob Williams",
    movie_id: "24",
  },
  {
    id: "35",
    rating: 8,
    content: "Suspenseful and thought-provoking",
    reviewer_name: "Emma Thompson",
    movie_id: "25",
  },
];

module.exports = {movies, directors, reviews};
